### ISSUE TITLE
Add (default) no defense against offense constraint

### ISSUE THREAD

**Issue by BenBrostoff** [BenBrostoff/draftfast#107]
Applies to MLB, NHL, soccer and likely more. User should be able to override since there are definitely players who don't mind having a starting pitcher face hitter in lineups, especially for cash games.

**Comment by sharkiteuthis** [comment]
@BenBrostoff Fixed by #108?

**Comment by sharkiteuthis** [comment]
fixed for NFL by #123

**Comment by sharkiteuthis** [comment]
NHL and soccer both appear to be implemented but untested

**Comment by BenBrostoff** [comment]
This can be done via `CustomRule` also so going to close.
