### ISSUE TITLE
lineup_constraints module not found

### ISSUE THREAD

**Issue by robotfactory** [BenBrostoff/draftfast#132]
The lineup_constraints module file is misnamed lineup_constaints.py. This misspelling is actually found in some other files like optimize.py and optimizer.py but others refer to it as the correct spelling.

When spelling the module name correctly a "module not found" error occurs.

**Comment by BenBrostoff** [comment]
@robotfactory Great catch; I suck at spelling. Fixed with https://github.com/BenBrostoff/draftfast/commit/df733943c96876948b8d5813ecc0655bbdd18c95 .

**Comment by robotfactory** [comment]
Oh, uh... I just submitted PR #133. Ha.
