### ISSUE TITLE
No solution found

### ISSUE THREAD

**Issue by dimitry-ishenko** [BenBrostoff/draftfast#137]
Total newb here. Tried to run your tool and got the above error message.
Here's the link with downloaded salaries.csv file: https://repl.it/@dimitry_ishenko/no-workie

Am I doing something wrong?

**Comment by BenBrostoff** [comment]
@dimitry-ishenko You need to add the NHL rules to the `ruleset` arg in `salary_download.generate_players_from_csvs` - this unfortunately is undocumented :-(. Here's a [repl.it with the fix](https://repl.it/@BenBrostoff/no-workie). Let me look into a way to change this behavior more obvious or somehow document it.

**Comment by dimitry-ishenko** [comment]
@BenBrostoff oh that's a pretty simple fix. Maybe just throw and exception if the ruleset is not defined?

**Comment by BenBrostoff** [comment]
Definitely, I can go that route 👍

**Comment by malpaso** [comment]
I've added a different sport & site and I'm using the run_multi() and it's returning 'No solution found'. I'm finding it really hard to diagnose why. I have the NBA working for the same site. The projections and salary files are identical in structure. At a loss to find out what the solver is 'seeing'... @BenBrostoff Any ideas on how I can better debug this?

**Comment by BenBrostoff** [comment]
@malpaso Just to be clear, is this working for `run` and not `run_multi`? If so it's possible there is a bug. If not, I would recommend creating the smallest example possible using manually created `Player`s (with the number of players equal to the roster size). I'm not saying the bug is with the CSV ingestion but if we do this first we can at least rule it out. It would also help if you could post your branch with the `No solution` example case and I can take a look.

**Comment by malpaso** [comment]
@BenBrostoff Thanks for replying Ben. Here is the branch on my fork with the changes. I'm getting 'no solution found' for `run` as well. [https://github.com/malpaso/draftfast/tree/aus](url)

**Comment by BenBrostoff** [comment]
@malpaso Got this to work on repl.it - [see link here](https://repl.it/@BenBrostoff/AllWarlikeDemoware-3). I think your issue may have been using `general_position_limits`. This is meant for sports where players can have position designations that cover multiple positions (ex. a `SF` or a `PF` are both `F`).

**Comment by BenBrostoff** [comment]
Closing this since we're now throwing on missing rulesets and this issue was related to a bad param.
