### ISSUE TITLE
How to implement randomness and all exposure

### ISSUE THREAD

**Issue by JoeAndrei** [BenBrostoff/draftfast#163]
Hello, How are you?
I hope you are safe from corona virus.
I have a few questions.
1) How to implement randomness and all exposure?
2) How to implement player id with player model without csv uploader and downloader?

Please help me.
Thanks

**Comment by BenBrostoff** [comment]
Hey Joe -

- Randomness - there are a few ways you could approach this - my preference is to use Python's built-in `random` and overwrite each `Player`'s `.proj`
- Exposure - I generally like to use `Counter` to do a frequency count on each iteration and then update `LineupConstraints` accordingly
- Player ID - remember that uploaders and downloaders are optional. You can always construct your own pool by just instantiating a list of `Player`s. IDs are whatever you want to set them as - could be a database id, using Python's `id`, etc.

**Comment by JoeAndrei** [comment]
Thanks for your reply.
I am clear about Randomness and Player ID
I am using exposure_bounds for individual exposure.
But I wanna set all exposure.
How can I use Counter to do a frequency count on each iteration
Could you explain, please about it. Thanks

**Comment by BenBrostoff** [comment]
Hey @JoeAndrei - since this isn't an issue with the core library, closing issue - feel free to ping me on Slack on this.
