### ISSUE TITLE
MLB Fanduel Optimization

### ISSUE THREAD

**Issue by robfreed10** [BenBrostoff/draftfast#164]
How can I account for pitchers who are not expected to pitch in the game tonight?
How can I account for players who's game has been postponed 
Thanks, 

Robert

**Comment by BenBrostoff** [comment]
Hey @robfreed10 - determining players you do or don't want in your player pool is up to you and not part of this library. I'd check out Rotogrinders or other services that offer updates on who is playing for a specific game. If you have a data feed, you can integrate this into a script that uses DraftFast.
