### ISSUE TITLE
[Question] Numpy version requirement

### ISSUE THREAD

**Issue by dttyszka** [BenBrostoff/draftfast#172]
New to this repo, but find the code very useful! I did notice the numpy version requirement==1.15.4, and this prevents pandas and draftfast from co-existing in the same env. What drives the requirement on that version of NumPy?

Thanks in advance!

**Comment by BenBrostoff** [comment]
Nothing as far as I know - upgrading is probably fine here, I will take a
look tomorrow - thanks for catching!

**Comment by BenBrostoff** [comment]
@dttyszka I haven't had time to work on this but will gladly accept a PR if it passes the build!

**Comment by BenBrostoff** [comment]
`numpy` is now on 1.24 and intending to keep upgrading, going to close here.
