### ISSUE TITLE
Fanduel csv_parse no longer works

### ISSUE THREAD

**Issue by sam1rm** [BenBrostoff/draftfast#189]
Here is the loading template i downloaded from fanduel 
[FanDuel-NBA-2022-05-21-76433-entries-upload-template.csv](https://github.com/BenBrostoff/draftfast/files/8748340/FanDuel-NBA-2022-05-21-76433-entries-upload-template.csv)

Here is the screenshot of the error when I try to run your first example on the README.
![Screen Shot 2022-05-21 at 4 05 15 PM](https://user-images.githubusercontent.com/1094573/169668949-f60f40e2-c2fc-4baa-b4f4-8ae446a42893.png)
 
I guess I'll look into it now, but any advise from someone who contributed or built this, would be greatly appreciated.

**Comment by BenBrostoff** [comment]
The CSVs used here are meant to be the ones you would download with the player list as opposed to a CSV for contests you've already entered and want to alter. If you take a look at some of the tests, you can see the expected CSV structure.

If you're looking to modify lineups, DraftFast can help with this, but it's not part of the core library at the moment. I would recommend creating a list of `Player`s on your own and feeding that into `optimize` with whatever settings you want.

**Comment by BenBrostoff** [comment]
Going to close for the time being but feel free to open another issue if you have a specific feature request around modifying existing lineups.

**Comment by sam1rm** [comment]
Thanks for the rapid reply! 

I've been using the `Player` instead, and just modifying the codebase to support Fan Duel Single Entry. I just need to find out how to create Custom Rules to support the multipliers for the first 3/5 entries [MVP @2x, star @1.5x and pro @1.2x]

That would be the feature request, but I'll go ahead and take a stab at examining the entirety of the codebase, and submit a PR soon. 

Thanks!

**Comment by BenBrostoff** [comment]
Awesome, thank you!
