### ISSUE TITLE
Could not find a version that satisfies the requirement ortools==9.0.9048

### ISSUE THREAD

**Issue by kilabyte** [BenBrostoff/draftfast#196]
Tried on windows and mac m1 same results. I can mod the req files but other things start to blow up. Im just running the instructed `pip install draftfast`

**Comment by ramGoli** [comment]
I just downloaded the repo and ran it instead when faced with the same issue.

**Comment by BenBrostoff** [comment]
Hey all - I will look into this but note the tests run against a Docker
container and use the same dependencies. If you try the Docker setup and
review what’s happening in travis.yml this should be working at least with
that environment

**Comment by BenBrostoff** [comment]
@kilabyte @ramGoli [I spot-checked this on a clean Repl.it shell and this works](https://replit.com/@BenBrostoff/ModernLegalPerimeter#main.py). What Python version are you using here?

**Comment by kilabyte** [comment]
Using 3.9.13 and 3.10.0.

I have a feeling it's my m1 mac. Been messing around with it all day and I can only get it working in a Rosetta terminal calling 'pip install draftfast==3.7.11' 

Running the Docker compose from the repo using the dockerfile to fill the image on the Apple M1 also causes massive issues.

**Comment by BenBrostoff** [comment]
On my end I run this on Rosetta since I also had issues with M1 (there's a thread about it here https://github.com/google/or-tools/issues/2332) - [for Docker I had to run like in this gist](https://gist.github.com/BenBrostoff/5f224aa87ce243d90890566f6938ecab).

You said though this also happened on Windows?

**Comment by kilabyte** [comment]
ya it was the same error on windows that could also be from the WSL. I have moved over to pydfs instead and have that working. :( I'll keep an eye on the repo for changes but we can close this for now
