### ISSUE TITLE
Fan Duel CSV Upload

### ISSUE THREAD

**Issue by Jzilllah** [BenBrostoff/draftfast#197]
Very new to coding here, so this may be a simple issue, but im having trouble importing Fan duel CSV.

Here is the error im getting:

![Screenshot (261)](https://user-images.githubusercontent.com/73140742/190028679-7a5433ec-f740-4bb4-b7a8-a5b0b7987617.png)

**Comment by BenBrostoff** [comment]
Can you attach the CSV you're attempting to ingest? It looks like the header doesn't have `Position` as a column name.

**Comment by Jzilllah** [comment]
both csv's i used appear to have position.

I used the below sheet for this attempt:

[FDweek2.csv](https://github.com/BenBrostoff/draftfast/files/9566164/FDweek2.csv)

I read in a previous comment that it hasnt been designed for the lineup build csv so i also tried with this version and got a different error. I have attached 

[FDweek2.csv](https://github.com/BenBrostoff/draftfast/files/9566177/FDweek2.csv)

![Screenshot (262)](https://user-images.githubusercontent.com/73140742/190151186-25be4e22-e81f-452e-98c9-b51949ff1ebb.png)

I'll keep trying things out to see if I can fix it it may just be a simple error that i'm missing.

Thanks,
J

**Comment by BenBrostoff** [comment]
I think you need to invoke `game` with either `DRAFT_KINGS` or `FAN_DUEL` - `generate_players_from_csv` expects a `str` instead of a `Ruleset`. You can see an example here https://github.com/BenBrostoff/draftfast/blob/b3278d0913e85084394f047fb1bfd6808e56c6b7/draftfast/test/test_optimize.py#L102-L114

**Comment by ramGoli** [comment]
Try this path instead:
salary_file_location="C://Users//J//Desktop//fdplayersweek2.csv"

**Comment by ramGoli** [comment]
Nevermind, you need to do this:

game=rules.FAN_DUEL,
instead of
game=rules.FD_NFL_RULE_SET
