### ISSUE TITLE
Improve Docker setup

### ISSUE THREAD

**Issue by BenBrostoff** [BenBrostoff/draftfast#61]
- [ ] Volumize
- [ ] Add README instructions
- [ ] `docker-compose`

**Comment by robotfactory** [comment]
May I suggest also moving from Ubuntu to Alpine? Much smaller containers. I could see some issue with the depends for the solver, though. I don't know how easy it is to get the LP stuff working on such a minimal distro.

**Comment by sharkiteuthis** [comment]
I had it running on alpine at one point and we decided to move it back to ubuntu, I don't remember why and I don't think we documented it unfortunately.

**Comment by BenBrostoff** [comment]
Going to close this - I think what we have on CI is acceptable for trying new Python versions which is really the big use case here. Will accept PRs though if people want to contribute.
